### ISSUE TITLE
go-flags Error does not implement error interface

### ISSUE THREAD

**Issue by ichenq** [jessevdk/go-flags#222]
A typical usage is, when it is help flag command, just return, otherwise print the error message,
see code below:

```go
opts := NewOptions()
if _, err := flags.Parse(opts); err != nil {
    if e, ok := err.(flags.Error); ok {
        if e.Type == flags.ErrHelp { 
            return
        }
    }
    log.Fatalf("Parse flags: %v\n", err)
}
```

when compile with Go1.7 under Linux, the compiler said:
`flags.Error does not implement error (Error method has pointer receiver)`

**Comment by ichenq** [comment]
embarrassing, this is my mistake, the right code should be:
```go
if e, ok := err.(*flags.Error); ok {
}
```

**Comment by jessevdk** [comment]
Yes, errors bv are pointers. The example also shows this and the compiler error is pretty clear.
